name = "Tiny Tater Test servers (Adventure Pack)"
author = "Tiny Tater Testers"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a5b466ecda6f03d192fb0d2759a0032e82589df816f2b9560452e8e701abb23b"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"
