name = "Tiny Tater Test servers (Adventure Pack)"
author = "Tiny Tater Testers"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "73c0465bc32d6609210bd84ab6fa46b75ae44ad9ac9f207120f71129e52a01cb"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"
