name = "Tiny Tater Test servers (Adventure Pack)"
author = "Tiny Tater Testers"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bb6380e1f30b8a38afdf5a1a9afd2955b59c3548b87de5285281b8f5a1b9c4bc"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"
