name = "Tiny Tater Test servers (Adventure Pack)"
author = "Tiny Tater Testers"
version = "1.2.1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e9b3893ad91c26567b650af6357114b17f5a62ec26f8f7adf419559f505fb97a"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"
