name = "Tiny Tater Test servers (Adventure Pack)"
author = "Tiny Tater Testers"
version = "1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e036a6f243ad2a9ea9963e28529dc4f4b705eea7670fbda4b02d439d87912bc2"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"
