name = "Tiny Tater Test servers (Adventure Pack)"
author = "Tiny Tater Testers"
version = "1.2.1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ce65511cbb3fc7ee89cdb5423fc801c50350011dec3c17ccda7f42449dd782cc"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"
