name = "Tiny Tater Test servers (Adventure Pack)"
author = "Tiny Tater Testers"
version = "1.0.4"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "50c236abd6f083f0e7074b9d7b8d83cac822c11fb56f346ed2a973f27552c624"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"
