name = "Tiny Tater Test servers (Adventure Pack)"
author = "Tiny Tater Testers"
version = "1.0.3"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1663c4cdc68c7cfc24071a0751e160114a0e2c5bf006dfd9d6799a593e17d175"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"
