name = "Tiny Tater Test servers (Adventure Pack)"
author = "Tiny Tater Testers"
version = "1.1.2"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1ef9df4d902fe65ef176222d3d01444bca2444c8a28fc81387e011c1136ca882"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"
