name = "Tiny Tater Test servers (Adventure Pack)"
author = "Tiny Tater Testers"
version = "1.1.3"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "49b66055fe5acc13e17b5ac4b2f099cbcee1f8c5eca0b3ecf078b65ad6984f51"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"
