name = "Tiny Tater Test servers (Adventure Pack)"
author = "Tiny Tater Testers"
version = "1.1.2"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6f676eff16ada5db702904b9e8ad23b101c02581552d2f57b3231156a06e8027"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"
