name = "Tiny Tater Test servers (Adventure Pack)"
author = "Tiny Tater Testers"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "832c1fa104720957be5675eb84c776d32d214b6b2ec8c02b8b236d12478e269a"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"
