name = "Tiny Tater Test servers (Adventure Pack)"
author = "Tiny Tater Testers"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9a09aebb8ee3cb81a0748535251f89c346895a1bfdd44c85915f0021397dfb1c"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"
