name = "Tiny Tater Test servers (Adventure Pack)"
author = "Tiny Tater Testers"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1d921738ba497746eab1b3006f65f67da287f577d1b78aee7189feb886a1b409"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"
