name = "Tiny Tater Test servers (Adventure Pack)"
author = "Tiny Tater Testers"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "79ee0fe40188ea7962b4120d7f58f010245e867a69c3c674c5d982fead01ce33"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"
