name = "Tiny Tater Test servers (Adventure Pack)"
author = "Tiny Tater Testers"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "41a59477c80693da58fa77c8cf8698a2bb39a7e0a21872b8ef897d8001edf630"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"
