name = "Tiny Tater Test servers (Adventure Pack)"
author = "Tiny Tater Testers"
version = "1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d2b90862d8483ace19f0584dd67d4d2e4505f50a61700c27bb46529c649d4fee"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"
