name = "Tiny Tater Test servers (Adventure Pack)"
author = "Tiny Tater Testers"
version = "1.2.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6deb8591907fb3e46ce028dde7d4aa8947083fddff85f740035167dc77fd89c1"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"
