name = "Tiny Tater Test servers (Adventure Pack)"
author = "Tiny Tater Testers"
version = "1.0.1"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c22d2208c025b6284135ae83fdba9d30358e912e5d5a5e9661ca9b8f6fc54ef8"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"
