name = "Tiny Tater Test servers (Adventure Pack)"
author = "Tiny Tater Testers"
version = "1.1.3"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3a1683e5760713065cfb658996edf3659dab36bb9803cb6977df1e8352be76c8"

[versions]
fabric = "0.11.3"
minecraft = "1.16.5"
