name = "Age of Exile"
filename = "Age-Of-Exile-1.16.3-1.7.10.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3186/152/Age-Of-Exile-1.16.3-1.7.10.jar"
hash-format = "murmur2"
hash = "1277122589"

[update]
[update.curseforge]
file-id = 3186152
project-id = 397698
release-channel = "beta"
