name = "Automated Crafting"
filename = "automated-crafting-1.3.20+MC1.16.2-1.16.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3170/232/automated-crafting-1.3.20+MC1.16.2-1.16.5.jar"
hash-format = "murmur2"
hash = "3838799986"

[update]
[update.curseforge]
file-id = 3170232
project-id = 389435
release-channel = "beta"
