name = "Blur (Fabric)"
filename = "Blur-2.0.0-1.16.2+fabric.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3105/894/Blur-2.0.0-1.16.2+fabric.jar"
hash-format = "murmur2"
hash = "3266489427"

[update]
[update.curseforge]
file-id = 3105894
project-id = 393563
release-channel = "beta"
