name = "Compact Status Effects"
filename = "CompactStatusEffects-1.2.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3049/571/CompactStatusEffects-1.2.2.jar"
hash-format = "murmur2"
hash = "3897576333"

[update]
[update.curseforge]
file-id = 3049571
project-id = 398752
release-channel = "beta"
