name = "Extra Alchemy"
filename = "extraalchemy-fabric-1.16.4-1.3.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3106/777/extraalchemy-fabric-1.16.4-1.3.1.jar"
hash-format = "murmur2"
hash = "3192782590"

[update]
[update.curseforge]
file-id = 3106777
project-id = 247357
release-channel = "beta"
